version: "3.9"

services:
  #PHP service
  php:
    container_name: application
    build:
      context: .
      target: php
      args:
        - APP_ENV=${APP_ENV}
    environment:
      - APP_ENV=${APP_ENV}
      - CONTAINER_ROLE=app
    working_dir: /var/www
    volumes:
      - ./:/var/www/ #mount current directory to /var/www
      # - ./docker-files/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "8000:8000" # bind port 8000 to container 8000
    depends_on:
      - database
      - redis



  # Database server
  database:
    container_name: database
    image: mysql:latest
    ports:
      - 3306:3306 #bind local port 3306 to container port 3306
    environment:
      MYSQL_DB: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./storage/dbdata:/var/lib/mysql

  # Redis server
  redis:
    container_name: redis
    image: redis:alpine
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - ./storage/redis/data:/data
    # networks:
    #   - optix